[package]
name = "structecs"
version.workspace = true
edition.workspace = true

[dependencies]
dashmap = "6.1"
enum-table = "2.1"
parking_lot = "0.12"
structecs-macros = { path = "../structecs-macros" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "query_benchmark"
harness = false
