[package]
name = "structecs"
version.workspace = true
edition.workspace = true

[dependencies]
enum-table = "2.1"
rayon = "1.10"
structecs-macros = { path = "../structecs-macros" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "query_benchmark"
harness = false
